# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d8aYTZa-ekWQR3_cZyM63VaVyiLmIwCR

1. Manfaat penggunaan fungsi, yaitu membuat program lebih modular, mengurangi pengulangan kode, mudah dibaca, diuji, dan diperbaiki, serta memudahkan pembagian tugas saat kerja tim.
Cara kerja rekursi untuk faktorial, yaitu
Faktorial:
n! = n x (n-1) x (n-2) x ... x 1
Dengan rekursi:
faktorial(n) = n x faktorial(n-1)
Base case:
faktorial(0) = 1
"""

def faktorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * faktorial(n - 1)

# Input dari user
angka = int(input("Masukkan angka: "))
hasil = faktorial(angka)
print(f"Faktorial dari {angka} adalah {hasil}")

"""2. Penggunaan digunakan untuk mengulang proses input nilai siswa sebanyak 5 kali tanpa nulis kode berulang.
Contohnya: for i in range(5) artinya ulang 5 kali.
Sedangkan array dipakai untuk menyimpan banyak nilai dalam satu variabel. Bisa menyimpan semua nilai siswa, lalu dianalisis misalnya untuk mencari nilai tertinggi.
"""

# Membuat list kosong untuk menyimpan nilai
nilai_siswa = []

# Input nilai 5 siswa
for i in range(5):
    nilai = int(input(f"Masukkan nilai siswa ke-{i+1}: "))
    nilai_siswa.append(nilai)

# Mencari nilai tertinggi dan indeksnya
nilai_tertinggi = max(nilai_siswa)
siswa_tertinggi = nilai_siswa.index(nilai_tertinggi) + 1  # +1 karena indeks mulai dari 0

# Menampilkan hasil
print(f"Nilai tertinggi adalah {nilai_tertinggi}, didapatkan oleh siswa ke-{siswa_tertinggi}")

"""3. Struktur kontrol percabangan digunakan untuk mengambil keputusan berdasarkan kondisi tertentu. Dalam kasus ini, program harus mengecek apakah total belanja 500.000. Jika iya, maka diskon 10% tetap diberlakukan. Jika tidak, maka total bayar tetap."""

# Input total belanja
total_belanja = float(input("Masukkan total belanja: Rp"))

# Cek apakah dapat diskon
if total_belanja > 500000:
    diskon = 0.10 * total_belanja
    total_bayar = total_belanja - diskon
    print(f"Anda mendapat diskon 10% sebesar Rp{diskon:.0f}")
else:
    diskon = 0
    total_bayar = total_belanja
    print("Anda tidak mendapat diskon.")

# Tampilkan total yang harus dibayar
print(f"Total bayar: Rp{total_bayar:.0f}")



"""4. Agar kasir bisa menghitung total 3 barang, langkah-langkah algoritmanya sebagai berikut:
a. Mulai
b. Input harga barang pertama
c. Input harga barang kedua
d. Input harga barang ketiga
e. Hitung total pembayaran = barang1 + barang2 + barang3
f. Tampilkan total pembayaran
g. Selesai
"""

# Input harga 3 barang
barang1 = float(input("Masukkan harga barang 1: Rp"))
barang2 = float(input("Masukkan harga barang 2: Rp"))
barang3 = float(input("Masukkan harga barang 3: Rp"))

# Hitung total
total = barang1 + barang2 + barang3

# Tampilkan total pembayaran
print(f"Total pembayaran: Rp{total:.0f}")

"""5. Peran tipe data:
Float atau int digunakan untuk menyimpan nilai angka (nilai ujian).
Peran operator:
Operator aritmatika + dan / digunakan untuk menghitung rata-rata. Operator logika >= digunakan untuk mengecek apakah nilai memenuhi syarat kelulusan (rata-rata ≥ 75).
"""

# Input nilai dari 3 mata pelajaran
nilai1 = float(input("Masukkan nilai mata pelajaran 1: "))
nilai2 = float(input("Masukkan nilai mata pelajaran 2: "))
nilai3 = float(input("Masukkan nilai mata pelajaran 3: "))

# Hitung rata-rata
rata_rata = (nilai1 + nilai2 + nilai3) / 3

# Tampilkan hasil
print(f"Rata-rata nilai: {rata_rata:.2f}")

# Tentukan status kelulusan
if rata_rata >= 75:
    print("Status: Lulus")
else:
    print("Status: Tidak Lulus")